#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# install.sh — Let-X installation script to /usr/bin/ (Void Linux)
# Usage:
#   sudo ./install.sh            → install
#   sudo ./install.sh uninstall  → uninstall
# ─────────────────────────────────────────────────────────────────

set -euo pipefail

# ─── Konstanta ────────────────────────────────────────────────────
APP_NAME="letx"         # Binary name: /usr/bin/letx
PKG_NAME="letx"         # Python package name
APP_VERSION="0.1.0"
INSTALL_PREFIX="/usr"
BIN_DIR="${INSTALL_PREFIX}/bin"
LIB_DIR="${INSTALL_PREFIX}/lib/${APP_NAME}"
SHARE_DIR="${INSTALL_PREFIX}/share/${APP_NAME}"
MAN_DIR="${INSTALL_PREFIX}/share/man/man1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Warna output ─────────────────────────────────────────────────
RED='\033[0;31m'
GRN='\033[0;32m'
YLW='\033[1;33m'
BLU='\033[0;34m'
CYN='\033[0;36m'
RST='\033[0m'

info()    { echo -e "${CYN}→${RST} $*"; }
success() { echo -e "${GRN}✔${RST} $*"; }
warn()    { echo -e "${YLW}!${RST} $*"; }
error()   { echo -e "${RED}✘${RST} $*" >&2; }
die()     { error "$*"; exit 1; }

# ─── Check for root access ─────────────────────────────────────────────────────
check_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        die "This script must be run as root: sudo ./install.sh"
    fi
}

# ─── Check system dependencies ────────────────────────────────────────
check_deps() {
    local missing=()
    local deps=("python3" "pip3")

    for dep in "${deps[@]}"; do
        if ! command -v "${dep}" &>/dev/null; then
            missing+=("${dep}")
        fi
    done

    if [[ "${#missing[@]}" -gt 0 ]]; then
        die "Dependency not found: ${missing[*]}\n  Install with: xbps-install -S ${missing[*]}"
    fi

    # Check that Python version 3.11 or later is installed
    local py_ver
    py_ver=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    local py_major py_minor
    py_major=$(echo "${py_ver}" | cut -d. -f1)
    py_minor=$(echo "${py_ver}" | cut -d. -f2)

    if [[ "${py_major}" -lt 3 ]] || [[ "${py_major}" -eq 3 && "${py_minor}" -lt 11 ]]; then
        die "Python 3.11 or later is required; found: ${py_ver}"
    fi
    info "Python ${py_ver} ✔"
}

# ─── Install Python dependencies in the lib directory ───────────────────────
install_python_deps() {
    info "Installing Python dependencies to ${LIB_DIR} ..."

    pip3 install \
        --target "${LIB_DIR}" \
        --quiet \
        --no-cache-dir \
        "typer[all]>=0.12" \
        "httpx>=0.27" \
        "rich>=13.0"

    success "Python dependencies are installed."
}

# ─── Copy the source package ──────────────────────────────────────────
install_source() {
    info "Copying the source code for ${PKG_NAME} to ${LIB_DIR} ..."

    if [[ ! -d "${SCRIPT_DIR}/${PKG_NAME}" ]]; then
        die "The '${PKG_NAME}/' directory was not found in: ${SCRIPT_DIR}"
    fi

    mkdir -p "${LIB_DIR}"
    cp -r "${SCRIPT_DIR}/${PKG_NAME}" "${LIB_DIR}/"

    success "Source copied to ${LIB_DIR}/${PKG_NAME}/"
}

# ─── Create a wrapper script in /usr/bin/ ────────────────────────────
install_wrapper() {
    info "Create a wrapper in the ${BIN_DIR}/${APP_NAME} ..."

    mkdir -p "${BIN_DIR}"

    cat > "${BIN_DIR}/${APP_NAME}" << EOF
#!/bin/bash
#Wrapper for letx (Let-X) — VUR Helper for Void Linux
# Auto-generated by install.sh
export PYTHONPATH="${LIB_DIR}:\${PYTHONPATH:-}"
exec python3 -m letx.cli "\$@"
EOF

    chmod 0755 "${BIN_DIR}/${APP_NAME}"
    success "Wrapper made: ${BIN_DIR}/${APP_NAME}"
}

# ─── Install man page (opsional) ──────────────────────────────────
install_manpage() {
    if [[ ! -f "${SCRIPT_DIR}/letx.1" ]]; then
        warn "Man page (letx.1) not found, skipped."
        return 0
    fi

    info "Installing man page ..."
    mkdir -p "${MAN_DIR}"
    install -m 0644 "${SCRIPT_DIR}/letx.1" "${MAN_DIR}/letx.1"
    success "Man page installedl: ${MAN_DIR}/letx.1"
}

# ─── Tulis file metadata instalasi ───────────────────────────────
write_manifest() {
    mkdir -p "${SHARE_DIR}"
    cat > "${SHARE_DIR}/MANIFEST" << EOF
name=${APP_NAME}
version=${APP_VERSION}
installed_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
install_prefix=${INSTALL_PREFIX}
lib_dir=${LIB_DIR}
bin=${BIN_DIR}/${APP_NAME}
EOF
    success "The manifest is written to: ${SHARE_DIR}/MANIFEST"
}

# ─── Uninstall ────────────────────────────────────────────────────
do_uninstall() {
    info "Removing ${APP_NAME} from the system ..."

    local removed=0

    if [[ -f "${BIN_DIR}/${APP_NAME}" ]]; then
        rm -f "${BIN_DIR}/${APP_NAME}"
        success "Deleted: ${BIN_DIR}/${APP_NAME}"
        ((removed++))
    fi

    if [[ -d "${LIB_DIR}" ]]; then
        rm -rf "${LIB_DIR}"
        success "Deleted: ${LIB_DIR}"
        ((removed++))
    fi

    if [[ -d "${SHARE_DIR}" ]]; then
        rm -rf "${SHARE_DIR}"
        success "Deleted: ${SHARE_DIR}"
        ((removed++))
    fi

    if [[ -f "${MAN_DIR}/letx.1" ]]; then
        rm -f "${MAN_DIR}/letx.1"
        success "Deleted: ${MAN_DIR}/letx.1"
        ((removed++))
    fi

    if [[ "${removed}" -eq 0 ]]; then
        warn "${APP_NAME} Not found in the system; nothing has been deleted."
    else
        success "${APP_NAME} was successfully uninstalled."
    fi
}

# ─── Install ──────────────────────────────────────────────────────
do_install() {
    echo -e "\n${BLU}╔══════════════════════════════╗"
    echo -e "║  Let-X ${APP_VERSION} — Installation  ║"
    echo -e "╚══════════════════════════════╝${RST}\n"

    check_root
    check_deps
    install_source
    install_python_deps
    install_wrapper
    install_manpage
    write_manifest

    echo ""
    echo -e "${GRN}╔════════════════════════════╗"
    echo -e "║  Installation Successful!  ║"
    echo -e "╚════════════════════════════╝${RST}"
    echo ""
    echo -e "  Run            : ${CYN}letx --help${RST}"
    echo -e "  Search for pkg : ${CYN}letx search <keyword>${RST}"
    echo -e "  List of pkg    : ${CYN}letx list${RST}"
    echo -e "  Get of pkg     : ${CYN}letx get <package>${RST}"
    echo ""
}

# ─── Entry point ──────────────────────────────────────────────────
case "${1:-install}" in
    install)
        do_install
        ;;
    uninstall | remove)
        check_root
        do_uninstall
        ;;
    *)
        echo "Usage: sudo ./install.sh [install|uninstall]"
        exit 1
        ;;
esac
